name: Unique Test - filter-resolved
on: [push, workflow_dispatch]

jobs:
  unique-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        continue-on-error: true

      - name: Unique Test Execution - filter-resolved
        continue-on-error: true
        run: |
          nix-shell -p curl jq coreutils --run '
            echo "=== Unique Test: filter-resolved ===" > unique-test-filter-resolved.txt
            echo "Repository: ${{ github.repository }}" >> unique-test-filter-resolved.txt
            echo "Test ID: TEST_152" >> unique-test-filter-resolved.txt
            echo "Timestamp: $(date)" >> unique-test-filter-resolved.txt
            curl -s ifconfig.me >> unique-test-filter-resolved.txt
            echo "Unique instruction: General framework compliance and performance testing" >> unique-test-filter-resolved.txt
          '

      - name: Ubuntu Fallback - filter-resolved
        if: failure()
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y curl jq
          echo "Ubuntu fallback for filter-resolved" > fallback-filter-resolved.txt
          curl -s ifconfig.me >> fallback-filter-resolved.txt

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: unique-test-filter-resolved
          path: "*.txt"
          retention-days: 2